name: build go app for arm64

on:
    push:
        branches:
            - main
jobs:
    buld:
        runs-on: self-hosted

        steps:
        - name: Check out code
          uses: actions/checkout@v3

        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21.0'

        - name: Build go app
          run: go build -o goapp

        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            name: goapp
            path: goapp
